BiblioMit/Models/Entities/Centres/Company.cs
using BiblioMit.Extensions;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BiblioMit.Models
{
    public class Company
    {
        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [DisplayFormat(DataFormatString = "{0,9:N0}")]
        [Display(Name = "RUT")]
        public int Id { get; set; }
        [Display(Name = "Business Name")]
        public string? BusinessName { get; private set; }
        public void SetBusinessName(string? value)
        {
            if (value == null)
            {
                return;
            }

            NormalizedBusinessName = value.RemoveDiacritics().ToUpperInvariant();
            BusinessName = value;
        }
        [Display(Name = "Trade Name")]
        public string? TradeName { get; private set; }
        public void SetTradeName(string value)
        {
            NormalizedTradeName = value.RemoveDiacritics().ToUpperInvariant();
            TradeName = value;
        }
        [Display(Name = "Acronym")]
        public string? Acronym { get; private set; }
        public void SetAcronym(string value)
        {
            Acronym = value?.ParseAcronym();
        }
        [Display(Name = "Address")]
        public string? Address { get; set; }
        public string? NormalizedBusinessName { get; private set; }
        public string? NormalizedTradeName { get; private set; }
        [Display(Name = "Farming Centres")]
        public virtual ICollection<Psmb> Psmbs { get; } = new List<Psmb>();
        public string GetRUT()
        {
            return Id.RUTFormat();
        }
        public string GetDV()
        {
            return Id.RUTGetDigit();
        }
    }
}

BiblioMit/Controllers/CentresController.cs
using BiblioMit.Data;
using BiblioMit.Models;
using BiblioMit.Models.Entities.Centres;
using BiblioMit.Models.VM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BiblioMit.Controllers
{
    [Authorize(Roles = nameof(RoleData.Administrator), Policy = nameof(UserClaims.Centres))]
    public class CentresController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CentresController(ApplicationDbContext context)
        {
            _context = context;
        }
        [HttpGet]
        [AllowAnonymous]
        public IActionResult GetMap(PsmbType type, int[] c, int[] i)
        {
            if (c == null || i == null)
            {
                throw new ArgumentNullException($"Argument c {c} and i {i} cannot be null");
            }

            IQueryable<Psmb> list = type switch
            {
                PsmbType.Farm => GetEntitiesAsync<Farm>(c, i),
                PsmbType.ResearchCentre => GetEntitiesAsync<ResearchCentre>(c, i),
                _ => GetEntitiesAsync<Psmb>(c, i)
            };
            return Json(list
                .Select(f =>
                    new GMapPolygonCentre
                    {
                        Id = f.Code,
                        Name = f.Name,
                        BusinessName = f.Company != null ? f.Company.BusinessName : null,
                        Rut = f.CommuneId != null ? f.CommuneId.Value : 0,
                        Comuna = f.Commune != null ? f.Commune.Name : null,
                        ComunaId = f.CommuneId != null ? f.CommuneId.Value : 0,
                        Provincia = f.Commune != null && f.Commune.Province != null ? f.Commune.Province.Name : null,
                        Region = f.Commune != null && f.Commune.Province != null && f.Commune.Province.Region != null ? f.Commune.Province.Region.Name : null,
                        Code = f.Code,
                        Position = f.Polygon != null ? f.Polygon.Vertices.OrderBy(o => o.Order).Select(o =>
                        new GMapCoordinate
                        {
                            Lat = o.Latitude,
                            Lng = o.Longitude
                        }) : null,
                    }));
        }
        private IQueryable<Psmb> GetPsmbs<TEntity>(int[] c, int[] i)
            where TEntity : Psmb
        {
            ViewData["c"] = string.Join(",", c);
            ViewData["i"] = string.Join(",", i);
            return GetEntitiesAsync<TEntity>(c, i);
        }
        private IQueryable<TEntity> GetEntitiesAsync<TEntity>(int[] c, int[] i)
            where TEntity : Psmb
        {
            IQueryable<TEntity> centres = _context.Set<TEntity>()
                        .Where(a => a.PolygonId.HasValue
                && a.CompanyId.HasValue);
            foreach (int sc in c)
            {
                centres = centres.Where(a => a.CommuneId.HasValue && a.CommuneId.Value == sc);
            }
            foreach (int si in i)
            {
                centres = centres.Where(a => a.CommuneId.HasValue && a.CommuneId.Value == si);
            }
            return centres;
        }
        [HttpGet]
        public IActionResult Producers(int[] c, int[] i) => View(GetPsmbs<Farm>(c, i));
        // GET: Centres
        [AllowAnonymous]
        [HttpGet]
        public IActionResult Research(int[] c, int[] i) => View(GetPsmbs<ResearchCentre>(c, i));
        // GET: Centres/Details/5
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Farm? centre = await _context.Farms
                .Include(c => c.Company)
                .Include(c => c.Polygon)
                .Include(c => c.Contacts)
                .SingleOrDefaultAsync(m => m.Id == id).ConfigureAwait(false);
            if (centre is null)
            {
                return NotFound();
            }

            return View(centre);
        }

        // GET: Centres/Create
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Create()
        {
            ViewData["ComunaId"] = new SelectList(_context.Communes, "Id", "Name");

            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Id");
            return View();
        }

        // POST: Centres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> Create([Bind("Id,ComunaId,Type,Url,Acronym,CompanyId,Name,Address")] ResearchCentre centre)
        {
            if (centre is null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Add(centre);
                await _context.SaveChangesAsync().ConfigureAwait(false);
                return RedirectToAction("Index");
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Id", centre.CompanyId);
            return View(centre);
        }

        // GET: Centres/Edit/5
        [Authorize(Roles = nameof(RoleData.Administrator) + "," + nameof(RoleData.Editor), Policy = nameof(UserClaims.Centres))]
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Farm? centre = await _context.Farms.SingleOrDefaultAsync(m => m.Id == id).ConfigureAwait(false);
            if (centre is null)
            {
                return NotFound();
            }

            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Id", centre.CompanyId);
            ViewData["ComunaId"] = new SelectList(_context.Communes, "Id", "Name", centre.CommuneId);
            return View(centre);
        }

        // POST: Centres/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        [Authorize(Roles = nameof(RoleData.Administrator) + "," + nameof(RoleData.Editor), Policy = nameof(UserClaims.Centres))]
        public async Task<IActionResult> Edit(int id, [Bind("ComunaId,Type,Url,Acronym,CompanyId,Name,Address")] ResearchCentre centre)
        {
            if (id != centre.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(centre);
                    await _context.SaveChangesAsync().ConfigureAwait(false);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CentreExists(centre.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Id", centre.CompanyId);
            return View(centre);
        }

        // GET: Centres/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            bool isAuthorized = User.IsInRole(RoleData.Administrator.ToString());
            if (!isAuthorized)
            {
                return RedirectToAction("AccessDenied", "Account");
            }

            if (id == null)
            {
                return NotFound();
            }

            Farm? centre = await _context.Farms
                .Include(c => c.Company)
                .Include(c => c.Commune)
                    .ThenInclude(c => c.Province)
                    .ThenInclude(c => c.Region)
                .SingleOrDefaultAsync(m => m.Id == id).ConfigureAwait(false);
            if (centre is null)
            {
                return NotFound();
            }

            return View(centre);
        }

        // POST: Centres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Farm? centre = await _context.Farms.SingleOrDefaultAsync(m => m.Id == id).ConfigureAwait(false);
            if (centre is not null)
            {
                _context.Farms.Remove(centre);
            }

            await _context.SaveChangesAsync().ConfigureAwait(false);
            return RedirectToAction("Index");
        }

        private bool CentreExists(int id)
        {
            return _context.Farms.Any(e => e.Id == id);
        }
    }
}

BiblioMit/Controllers/CompaniesController.cs
using BiblioMit.Data;
using BiblioMit.Extensions;
using BiblioMit.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BiblioMit.Controllers
{
    [Authorize(Policy = nameof(UserClaims.Institutions))]
    public class CompaniesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CompaniesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Companies
        [Authorize(Roles = nameof(RoleData.Administrator))]
        [Authorize(Roles = nameof(RoleData.Editor))]
        [Authorize(Roles = nameof(RoleData.Guest))]
        [HttpGet]
        public IActionResult Index()
        {
            return View(_context.Companies
                .Include(c => c.Psmbs)
                    .ThenInclude(c => c.Polygon)
                .AsNoTracking());
        }

        // GET: Companies/Details/5
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Company? company = await _context.Companies
                .Include(c => c.Psmbs)
                    .ThenInclude(c => c.Contacts)
                .Include(c => c.Psmbs)
                    .ThenInclude(c => c.Commune)
                        .ThenInclude(c => c.Province)
                            .ThenInclude(c => c.Region)
                .SingleOrDefaultAsync(m => m.Id == id).ConfigureAwait(false);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // GET: Companies/Create
        [Authorize(Roles = nameof(RoleData.Administrator))]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        [Authorize(Roles = nameof(RoleData.Administrator))]
        public async Task<IActionResult> Create([Bind("Id,BsnssName,Acronym")] CompanyViewModel company)
        {
            if (company == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                (int rut, string dv)? rut = company.RUT?.RUTUnformat();
                if (rut.HasValue)
                {
                    Company corp = new()
                    {
                        Id = rut.Value.rut
                    };
                    corp.SetBusinessName(company.BsnssName);
                    if (company.Acronym is not null)
                    {
                        corp.SetAcronym(company.Acronym);
                    }

                    _context.Add(corp);
                    await _context.SaveChangesAsync().ConfigureAwait(false);
                    return RedirectToAction("Index");
                }
            }
            return View(company);
        }

        // GET: Companies/Edit/5
        [Authorize(Roles = nameof(RoleData.Administrator))]
        [Authorize(Roles = nameof(RoleData.Editor))]
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Company? company = await _context.Companies.FindAsync(id).ConfigureAwait(false);
            if (company == null)
            {
                return NotFound();
            }

            CompanyViewModel comp = new()
            {
                RUT = company.Id.RUTFormat(),
                BsnssName = company.BusinessName
            };
            return View(comp);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        [Authorize(Roles = nameof(RoleData.Administrator))]
        [Authorize(Roles = nameof(RoleData.Editor))]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BsnssName,Acronym")] Company company)
        {
            if (company == null || id != company.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(company);
                    await _context.SaveChangesAsync().ConfigureAwait(false);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        [Authorize(Roles = nameof(RoleData.Administrator))]
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Company? company = await _context.Companies
                .SingleOrDefaultAsync(m => m.Id == id).ConfigureAwait(false);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        [Authorize(Roles = nameof(RoleData.Administrator))]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Company? company = await _context.Companies.FindAsync(id).ConfigureAwait(false);
            if (company == null)
            {
                return NotFound();
            }

            _context.Companies.Remove(company);
            await _context.SaveChangesAsync().ConfigureAwait(false);
            return RedirectToAction("Index");
        }

        private bool CompanyExists(int id)
        {
            return _context.Companies.Any(e => e.Id == id);
        }
    }
}

BiblioMit/Views/Companies/Create.cshtml
@model BiblioMit.Models.CompanyViewModel

@{
    ViewData["Title"] = "Crear";
}
<h2>Crear</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Compa&ntilde;&iacute;a o Instituci&oacute;n</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="RUT" class="col-md-2 control-label"></label>
            <div class="col-md-7">
                <input asp-for="RUT" class="form-control" />
                <span asp-validation-for="RUT" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BsnssName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BsnssName" class="form-control" />
                <span asp-validation-for="BsnssName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Acronym" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Acronym" class="form-control" />
                <span asp-validation-for="Acronym" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" onclick="empty()" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Volver al listado de Compa&ntilde;&iacute;as e Instituci&oacute;nes</a>
</div>

<partial name="_ValidationScriptsPartial" />

BiblioMit/Views/Companies/Delete.cshtml
@model BiblioMit.Models.Company

@{
    ViewData["Title"] = "Eliminar";
}

<h2>Eliminar</h2>

<h3>&iquest;Est&aacute;s seguro que quieres eliminar esta Compa&ntilde;&iacute;a o Instituci&oacute;n?</h3>
<div>
    <h4>Compa&ntilde;&iacute;a o Instituci&oacute;n</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GetRUT())
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BusinessName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BusinessName)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Acronym)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Acronym)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            <a asp-action="Index">Volver al listado de Compa&ntilde;&iacute;as e Instituci&oacute;nes</a>
        </div>
    </form>
</div>

BiblioMit/Views/Companies/Details.cshtml
@model BiblioMit.Models.Company

@{
    ViewData["Title"] = "Detalles";
}
<h1>Detalles</h1>

<div class="container">
    <div class="row">
        <div class="col-lg-1 col-md-1 col-sm-2 col-xs-3">
            <img src="~/images/ico/@(Model.Acronym).svg" alt="corfo" class="img-responsive" />
        </div>
        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-9">
            <h2>Compa&ntilde;&iacute;a o Instituci&oacute;n</h2>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.BusinessName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.BusinessName)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Id)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Id)-@Model.Id.RUTGetDigit()
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Acronym)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Acronym)
                </dd>
                <dt>
                    N&uacute;mero de Centros
                </dt>
                <dd>
                    @Model.Psmbs.Count
                </dd>
            </dl>
        </div>
    </div>
    <div class="row">
        <h3>Centros</h3>
        <table class="table">
            <thead>
                <tr>
                    <th class="hidden-xs">Tipo</th>
                    <th>Nombre</th>
                    <th>Direcci&oacute;n</th>
                    <th>Contactos</th>
                </tr>
            </thead>
            @foreach (Psmb item in Model.Psmbs)
            {
                <tbody>
                    <tr>
                        <td class="hidden-xs" style="vertical-align:middle">@item.Discriminator</td>
                        <td style="vertical-align:middle">
                            <a href="@(((BiblioMit.Models.Entities.Centres.ResearchCentre)item).Url)"><strong>@item.Name (@item.Acronym)</strong></a><br />
                            <text class="hidden-lg hidden-md" style="font-size:smaller">@item.Discriminator</text>
                            <a style="font-size:smaller" asp-controller="Centres" asp-action="Details" asp-route-id="@item.Id">Detalles</a>
                        </td>
                        <td style="vertical-align:middle">
                            <a target="_blank" rel="noopener" href="https://www.google.cl/maps/place/@item.Address, @item.Commune.Name">@item.Address, @item.Commune.GetFullName()</a><br/>
                        </td>
                        <td style="font-family:'Arial Narrow'">
                            @foreach (Contact contact in item.Contacts)
                            {
                                <strong>@contact.Position</strong>
                                <br/>
                                @contact.Name @contact.Last
                                <br/>
                                <a href="emailto:@contact.Email">@contact.Email</a><br/>
                                <a href="tel:@contact.Phone">
                                    @String.Format("{0:(+##) ##### ####}", contact.Phone)
                                </a>
                                <br/>
                                }
</td>
                    </tr>
                </tbody>
            }
        </table>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Index">Volver al listado de Compa&ntilde;&iacute;as e Instituci&oacute;nes</a>
</div>

BiblioMit/Views/Companies/Edit.cshtml
@model BiblioMit.Models.Company

@{
    ViewData["Title"] = "Editar";
}
<h2>Editar</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Compa&Ntilde;&iacute;a o Instituci&Oacute;n</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Id" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BusinessName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BusinessName" class="form-control" />
                <span asp-validation-for="BusinessName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Acronym" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Acronym" class="form-control" />
                <span asp-validation-for="Acronym" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Volver al listado de Compa&Ntilde;&iacute;as e Instituci&Oacute;nes</a>
</div>

    <partial name="_ValidationScriptsPartial" />

BiblioMit/Views/Companies/Index.cshtml
@model IEnumerable<BiblioMit.Models.Company>

@{
    ViewData["Title"] = "Compañías e Instituciones";
}
<h2 id="maintitle">Listado de Compa&ntilde;&iacute;as e Instituciones</h2>

<p>
    <a asp-action="Create">Nueva entrada</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Localizer[Html.DisplayNameFor(model => model.BusinessName)]
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                Centros
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Company item in Model)
{
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BusinessName)
                </td>
                <td>
                    @item.GetRUT()
                </td>
                <td>
                    <a href="@Url.Action("Index", "Centres", null, null)">@Html.DisplayFor(modelItem => item.Psmbs.Count)</a>
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

BiblioMit/Views/Companies/_RUT.cshtml
@model CompanyViewModel

El RUT @Model.RUT no es válido.
Por favor verifique los datos de la compa&ntilde;&iacute;a @Model.BsnssName