BiblioMit/Controllers/CompaniesController.cs
using BiblioMit.Data;
using BiblioMit.Extensions;
using BiblioMit.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BiblioMit.Controllers
{
    [Authorize(Policy = nameof(UserClaims.Institutions))]
    public class CompaniesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CompaniesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Companies
        [Authorize(Roles = nameof(RoleData.Administrator))]
        [Authorize(Roles = nameof(RoleData.Editor))]
        [Authorize(Roles = nameof(RoleData.Guest))]
        [HttpGet]
        public IActionResult Index()
        {
            return View(_context.Companies
                .Include(c => c.Psmbs)
                    .ThenInclude(c => c.Polygon)
                .AsNoTracking());
        }

        // GET: Companies/Details/5
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Company? company = await _context.Companies
                .Include(c => c.Psmbs)
                    .ThenInclude(c => c.Contacts)
                .Include(c => c.Psmbs)
                    .ThenInclude(c => c.Commune)
                        .ThenInclude(c => c.Province)
                            .ThenInclude(c => c.Region)
                .SingleOrDefaultAsync(m => m.Id == id).ConfigureAwait(false);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // GET: Companies/Create
        [Authorize(Roles = nameof(RoleData.Administrator))]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        [Authorize(Roles = nameof(RoleData.Administrator))]
        public async Task<IActionResult> Create([Bind("Id,BsnssName,Acronym")] CompanyViewModel company)
        {
            if (company == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                (int rut, string dv)? rut = company.RUT?.RUTUnformat();
                if (rut.HasValue)
                {
                    Company corp = new()
                    {
                        Id = rut.Value.rut
                    };
                    corp.SetBusinessName(company.BsnssName);
                    if (company.Acronym is not null)
                    {
                        corp.SetAcronym(company.Acronym);
                    }

                    _context.Add(corp);
                    await _context.SaveChangesAsync().ConfigureAwait(false);
                    return RedirectToAction("Index");
                }
            }
            return View(company);
        }

        // GET: Companies/Edit/5
        [Authorize(Roles = nameof(RoleData.Administrator))]
        [Authorize(Roles = nameof(RoleData.Editor))]
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Company? company = await _context.Companies.FindAsync(id).ConfigureAwait(false);
            if (company == null)
            {
                return NotFound();
            }

            CompanyViewModel comp = new()
            {
                RUT = company.Id.RUTFormat(),
                BsnssName = company.BusinessName
            };
            return View(comp);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        [Authorize(Roles = nameof(RoleData.Administrator))]
        [Authorize(Roles = nameof(RoleData.Editor))]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BsnssName,Acronym")] Company company)
        {
            if (company == null || id != company.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(company);
                    await _context.SaveChangesAsync().ConfigureAwait(false);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        [Authorize(Roles = nameof(RoleData.Administrator))]
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Company? company = await _context.Companies
                .SingleOrDefaultAsync(m => m.Id == id).ConfigureAwait(false);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        [Authorize(Roles = nameof(RoleData.Administrator))]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Company? company = await _context.Companies.FindAsync(id).ConfigureAwait(false);
            if (company == null)
            {
                return NotFound();
            }

            _context.Companies.Remove(company);
            await _context.SaveChangesAsync().ConfigureAwait(false);
            return RedirectToAction("Index");
        }

        private bool CompanyExists(int id)
        {
            return _context.Companies.Any(e => e.Id == id);
        }
    }
}

BiblioMit/Views/Publications/Agenda.cshtml
@using BiblioMit.Models.VM
@model IEnumerable<AgendaVM>

@{
    ViewData["Title"] = "Agenda de Ciencia y Tecnología";
}

<partial name="_Libs" model='new List<string> { "bootstrap-select", "bibliomit", "bibico", "bootstrap-select-localize" }' />

<div class="row">
    <div class="col-lg-9 col-md-12">
        <h2>@ViewData["Title"]</h2>
        <h4>Fondos Concursables de financiamiento Ciencia y Tecnología</h4>
    </div>
</div>

<form id="form" asp-action="Agenda" method="get" class="form-inline">
    <div class="input-group mb-3">
        <select id="fondos" name="fund" class="selectpicker form-control" multiple data-live-search="true" 
                tabindex="-98" data-actions-box="true" value="@ViewData["fund"]" title="Seleccionar Fondos …"
                data-selected-text-format="count > 4" data-size="5">
            <optgroup label="Fondos CONICYT &mdash; Comisión Nacional de Investigación Científica y Tecnológica">
                @{
                    Dictionary<string, Uri>.KeyCollection? items = ((Dictionary<string, Uri>?)ViewData["conicyt1"])?.Keys;
                    Dictionary<string, Uri>.KeyCollection? conicyt2items = ((Dictionary<string, Uri>?)ViewData["conicyt2"])?.Keys;
                    IEnumerable<BiblioMit.Models.Region>? regions = (IEnumerable<BiblioMit.Models.Region>?)ViewData["regiones"];
                }
                @if (items is not null) foreach (string item in items)
                {
                    <option data-icon="bib-conicyt-mono" data-tokens="conicyt" selected="@(((string[]?)ViewData["fund"])?.Contains(item))" 
                            data-subtext="@item" value="@item">@item.ToUpper()</option>
                }
                @if(conicyt2items is not null) foreach (string item in conicyt2items)
                {
                    <option data-icon="bib-conicyt-mono" data-tokens="conicyt" selected="@(((string[]?)ViewData["fund"])?.Contains(item))" 
                            data-subtext="@item" value="@item">@item.ToUpper()</option>
                }
            </optgroup>
            <optgroup label="Fondos CORFO &mdash; Coorporación de Fomento a la Producción">
                @if (regions is not null) foreach (Region region in regions)
                {
                    <option data-icon="bib-corfo-mono" data-tokens="corfo" selected="@(((string[]?)ViewData["fund"])?.Contains("corfo" + region.Id))"
                            value="@("corfo"+region.Id)">@((region.Id == 0) ? "Nacional" : region.GetFullName())</option>
                }
            </optgroup>
        </select>
        <select id="estado" name="stt" class="selectpicker form-control show-tick" tabindex="-98" value="@ViewData["stt"]" title="Elegir estado de concurso …">
            <option selected="@((string?)ViewData["stt"] == "abierto")" 
                    class="alert alert-success" data-icon="far fa-edit" value="abierto">Abiertos</option>
            <option selected="@((string?)ViewData["stt"] == "evaluacion")" 
                    class="alert alert-info" data-icon="far fa-eye fa-fw" value="evaluacion">En evaluaci&oacute;n</option>
            <option selected="@((string?)ViewData["stt"] == "adjudicado")" 
                    class="alert alert-warning" data-icon="fas fa-award" value="adjudicado">Adjudicados</option>
            <option selected="@((string?)ViewData["stt"] == "proximo")" 
                    class="alert alert-danger" data-icon="fa fa-calendar" value="proximo">Pr&oacute;ximos</option>
        </select>
        <button type="submit" value="Buscar" class="btn btn-primary btn-block" onclick="return empty();"><i class="fas fa-search"></i>  Buscar</button>
    </div>
</form>

@if (((string[]?)ViewData["fund"])?.Count() > 0)
{
    <button type="button" class="stat btn btn-block btn-link">
        <i class="fa fa-globe"></i> <strong>@String.Format("{0:n0}", Model.Count())</strong> Resultados en <strong>@(((string[]?)ViewData["fund"])?.Count())</strong> Reps.
    </button>
}

@if ((bool?)ViewData["any"] ?? false)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Fund)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Start)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.End)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (AgendaVM item in Model)
            {
                <tr>
                    <td>
                        <div class="img-with-text" style="float: left;padding-right:1vw;">
                            <a style="font-size:small" asp-controller="Companies" asp-action="Details" asp-route-id="@item.Company?.Id">
                                <span style="font-size:70px;" class="bib-@item.Company?.Acronym">
                                    <span class="path1"></span><span class="path2"></span><span class="path3"></span><span class="path4"></span><span class="path5"></span><span class="path6"></span>
                                </span>
                            </a>
                            <p style="font-size:smaller;">
                                <strong>@item.Company?.Acronym</strong>
                            </p>
                        </div>
                        <div>
                            <p style="margin-bottom:0px;float: left;max-width:30vw;text-align:justify">
                                <a target="_blank" rel="noopener" href="@Html.DisplayFor(modelItem => item.MainUrl)">
                                    @Html.DisplayFor(modelItem => item.Title)
                                </a>
                                <br />
                                @Html.DisplayFor(modelItem => item.Fund)
                                <br />
                                @item.Company?.Acronym (@if (item.Company is not null) Html.DisplayFor(modelItem => item.Company.BusinessName);)
                                <br />
                                @item.Description
                            </p>
                        </div>
                    </td>
                    <td>
                        @if (String.IsNullOrEmpty(item.Start.ToString()))
                        {
                            <text>&mdash;</text>
                        }
                        else
                        {
                            @Html.DisplayFor(modelItem => item.Start)
                        }
                    </td>
                    <td>
                        @if (String.IsNullOrEmpty(item.End.ToString()) | item.End == DateTime.MinValue)
                        {
                            <text>Abierto Todo el Año</text>
                        }
                        else
                        {
                            @Html.DisplayFor(modelItem => item.End)
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

BiblioMit/Views/Publications/_Clock.cshtml
<partial name="_Libs" model='new List<string> { "angular", "angular-flip-clock", "clock" }' />

<div class="myApp" ng-app="myApp">
    <div class="m-auto">
        <dy-flip-clock time="{{time}}"></dy-flip-clock>
    </div>
</div>

<input id="interval" value="@((int?)ViewData["interval"])" class="d-none"/>

BiblioMit/Views/Publications/_PagingPub.cshtml
<div class="btn-group d-flex" role="group" aria-label="Paging">
    <a asp-action="Index"
       asp-route-q="@ViewData["q"]"
       asp-route-pg="1"
       asp-route-src="@ViewData["srcs"]"
       asp-route-srt="@ViewData["srt"]"
       asp-route-asc="@ViewData["asc"]"
       class="paging btn btn-outline-secondary w-100 @ViewData["prevDisabled"]" role="button">
        &laquo;<text class="hidden-xs hidden-s hidden-sm"> @Localizer["First"]</text>
    </a>
    <a asp-action="Index"
       asp-route-q="@ViewData["q"]"
       asp-route-pg="@((int?)ViewData["pg"]) - 1)"
       asp-route-src="@ViewData["srcs"]"
       asp-route-srt="@ViewData["srt"]"
       asp-route-asc="@ViewData["asc"]"
       class="paging btn btn-outline-secondary w-100 @ViewData["prevDisabled"]" role="button">
        &lsaquo;<text class="hidden-xs hidden-s hidden-sm"> @Localizer["Previous"]</text>
    </a>
    @if ((int?)ViewData["low"] > 1)
    {
        <a class="paging btn btn-outline-secondary w-100 disabled" role="button"><text>&hellip;</text></a>
    }
    @for (int? i = (int?)ViewData["low"]; i <= (int?)ViewData["high"]; i++)
    {
        string disabled = "";
        if (i == (int?)ViewData["pg"])
        {
            disabled = "disabled";
        }
        <a asp-action="Index"
           asp-route-q="@ViewData["q"]"
           asp-route-pg="@i"
           asp-route-src="@ViewData["srcs"]"
           asp-route-srt="@ViewData["srt"]"
           asp-route-asc="@ViewData["asc"]"
           class="paging btn btn-outline-secondary w-100 @disabled" role="button">
            @i
        </a>
    }
    @if ((int?)ViewData["NoPages"] > (int?)ViewData["high"])
    {
        <a class="paging btn btn-outline-secondary w-100 disabled" role="button"><text>&hellip;</text></a>
    }
    <a asp-action="Index"
       asp-route-q="@ViewData["q"]"
       asp-route-pg="@((int?)ViewData["pg"]) + 1)"
       asp-route-src="@ViewData["srcs"]"
       asp-route-srt="@ViewData["srt"]"
       asp-route-asc="@ViewData["asc"]"
       class="paging btn btn-outline-secondary w-100 @ViewData["nextDisabled"]" role="button">
        <text class="hidden-xs hidden-s hidden-sm">@Localizer["Next"] </text>&rsaquo;
    </a>
    <a asp-action="Index"
       asp-route-q="@ViewData["q"]"
       asp-route-pg="@ViewData["NoPages"]"
       asp-route-src="@ViewData["srcs"]"
       asp-route-srt="@ViewData["srt"]"
       asp-route-asc="@ViewData["asc"]"
       class="paging btn btn-outline-secondary w-100 @ViewData["nextDisabled"]" role="button">
        <text class="hidden-xs hidden-s hidden-sm">@Localizer["Last"] </text>&raquo;
    </a>
</div>

BiblioMit/Views/Publications/_StatsGraph.cshtml
@using BiblioMit.Models.VM
@model Dictionary<Typep, int>


<partial name="_Pg" />

@this.Block("Scripts", @<script>
    var chart;
    var titles = [
        "@ViewData["all"] Total",
        "@ViewData["artscnt"] Artículos",
        "@ViewData["tesiscnt"] Tesis",
        "@ViewData["projcnt"] Proyectos",
        "@ViewData["patscnt"] Patentes"
    ];

    AmCharts.ready(function () {
        chart = new AmCharts.AmPieChart();
        chart.dataProvider = chartData[0];
        chart.valueField = "resultados";
        chart.titleField = "repositorio";
        chart.colorField = "color";
        chart.labelsEnabled = false;
        chart.balloonText = "[[title]]<br><span style='font-size:10px'><b>[[value]]</b> ([[percents]]%)</span>";
        chart.addTitle(titles[0]);
        chart.autoMargins = false;
        chart.marginTop = 0;
        chart.marginBottom = 0;
        chart.marginLeft = 0;
        chart.marginRight = 0;
        chart.pullOutRadius = 0;

        legend = new AmCharts.AmLegend();
        legend.divId = "legenddiv";
        legend.markerType = "circle";
        legend.position = "right";
        chart.legend = legend;

        chart.write("chartdiv");
    });

    function selectData(i) {
        chart.dataProvider = chartData[i];
        chart.validateData();
        $("#chartdiv tspan").html(titles[i]);
    }
</script>)